# Generated by Django 3.1.4 on 2020-12-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='url_status',
        ),
    ]
