# Generated by Django 3.1.4 on 2020-12-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_check', '0002_remove_url_url_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url_status',
            field=models.CharField(max_length=20, null=True, verbose_name='URL_status'),
        ),
    ]
