# Generated by Django 3.1.4 on 2020-12-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_check', '0003_url_url_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url_checker',
            field=models.BooleanField(default=True),
        ),
    ]
